# Generated by Django 6.0.3 on 2026-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_comment_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='plants', to='plants.country'),
        ),
    ]
