# Generated by Django 6.0.3 on 2026-04-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_country_plant_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care_level',
            field=models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MED', 'Medium'), ('HARD', 'Hard')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='light',
            field=models.CharField(blank=True, choices=[('DIR', 'Direct'), ('IND', 'Indirect'), ('LOW', 'Low Light')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='water',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MO', 'Moderate'), ('HIGH', 'High')], max_length=10, null=True),
        ),
    ]
